# Built with Jekyll 3.2.0

# [little reminder from mindzauber: don't forget, that if you use ' in the text, you should change 
# the beginning and ending ' into ". Else you might produce an error.]

# Setup
title:               mindzauber.
tagline:             'a website for talking taboos'
#description:         'mindzauber. is a website for no-no topics. it is for talking taboos.'
description:         "mindzauber. is a website for talking about the things people wouldn't want to talk about. it is about talking taboos."
url:                 'http://mindzauber.github.io'
baseurl:             '/ed'

# About/contact
author:
  name:              Peggy
  url:               https://twitter.com/peggyaster
  email:             mindzauber@gmail.com

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."


